// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: proto/judge.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Language int32

const (
	Language_LANGUAGE_UNSPECIFIED Language = 0
	Language_CPP                  Language = 1
	Language_JAVA                 Language = 2
	Language_PYTHON               Language = 3
	Language_GO                   Language = 4
)

// Enum value maps for Language.
var (
	Language_name = map[int32]string{
		0: "LANGUAGE_UNSPECIFIED",
		1: "CPP",
		2: "JAVA",
		3: "PYTHON",
		4: "GO",
	}
	Language_value = map[string]int32{
		"LANGUAGE_UNSPECIFIED": 0,
		"CPP":                  1,
		"JAVA":                 2,
		"PYTHON":               3,
		"GO":                   4,
	}
)

func (x Language) Enum() *Language {
	p := new(Language)
	*p = x
	return p
}

func (x Language) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Language) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_judge_proto_enumTypes[0].Descriptor()
}

func (Language) Type() protoreflect.EnumType {
	return &file_proto_judge_proto_enumTypes[0]
}

func (x Language) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Language.Descriptor instead.
func (Language) EnumDescriptor() ([]byte, []int) {
	return file_proto_judge_proto_rawDescGZIP(), []int{0}
}

type JudgeStatus int32

const (
	JudgeStatus_STATUS_UNSPECIFIED    JudgeStatus = 0
	JudgeStatus_ACCEPTED              JudgeStatus = 1
	JudgeStatus_WRONG_ANSWER          JudgeStatus = 2
	JudgeStatus_COMPILE_ERROR         JudgeStatus = 3
	JudgeStatus_TIME_LIMIT_EXCEEDED   JudgeStatus = 4
	JudgeStatus_MEMORY_LIMIT_EXCEEDED JudgeStatus = 5
	JudgeStatus_RUNTIME_ERROR         JudgeStatus = 6
	JudgeStatus_SYSTEM_ERROR          JudgeStatus = 7
)

// Enum value maps for JudgeStatus.
var (
	JudgeStatus_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "ACCEPTED",
		2: "WRONG_ANSWER",
		3: "COMPILE_ERROR",
		4: "TIME_LIMIT_EXCEEDED",
		5: "MEMORY_LIMIT_EXCEEDED",
		6: "RUNTIME_ERROR",
		7: "SYSTEM_ERROR",
	}
	JudgeStatus_value = map[string]int32{
		"STATUS_UNSPECIFIED":    0,
		"ACCEPTED":              1,
		"WRONG_ANSWER":          2,
		"COMPILE_ERROR":         3,
		"TIME_LIMIT_EXCEEDED":   4,
		"MEMORY_LIMIT_EXCEEDED": 5,
		"RUNTIME_ERROR":         6,
		"SYSTEM_ERROR":          7,
	}
)

func (x JudgeStatus) Enum() *JudgeStatus {
	p := new(JudgeStatus)
	*p = x
	return p
}

func (x JudgeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JudgeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_judge_proto_enumTypes[1].Descriptor()
}

func (JudgeStatus) Type() protoreflect.EnumType {
	return &file_proto_judge_proto_enumTypes[1]
}

func (x JudgeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JudgeStatus.Descriptor instead.
func (JudgeStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_judge_proto_rawDescGZIP(), []int{1}
}

type TaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId       string   `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Code        []byte   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Language    Language `protobuf:"varint,3,opt,name=language,proto3,enum=deep_oj.Language" json:"language,omitempty"`
	TimeLimit   int32    `protobuf:"varint,4,opt,name=time_limit,json=timeLimit,proto3" json:"time_limit,omitempty"`
	MemoryLimit int32    `protobuf:"varint,5,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	CacheKey    string   `protobuf:"bytes,6,opt,name=cache_key,json=cacheKey,proto3" json:"cache_key,omitempty"`
	ProblemId   uint32   `protobuf:"varint,7,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	TestCases   []string `protobuf:"bytes,8,rep,name=test_cases,json=testCases,proto3" json:"test_cases,omitempty"`
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_judge_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_judge_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_judge_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *TaskRequest) GetCode() []byte {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *TaskRequest) GetLanguage() Language {
	if x != nil {
		return x.Language
	}
	return Language_LANGUAGE_UNSPECIFIED
}

func (x *TaskRequest) GetTimeLimit() int32 {
	if x != nil {
		return x.TimeLimit
	}
	return 0
}

func (x *TaskRequest) GetMemoryLimit() int32 {
	if x != nil {
		return x.MemoryLimit
	}
	return 0
}

func (x *TaskRequest) GetCacheKey() string {
	if x != nil {
		return x.CacheKey
	}
	return ""
}

func (x *TaskRequest) GetProblemId() uint32 {
	if x != nil {
		return x.ProblemId
	}
	return 0
}

func (x *TaskRequest) GetTestCases() []string {
	if x != nil {
		return x.TestCases
	}
	return nil
}

type TaskResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId        string      `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status       JudgeStatus `protobuf:"varint,2,opt,name=status,proto3,enum=deep_oj.JudgeStatus" json:"status,omitempty"`
	ErrorMessage string      `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	TimeUsed     int32       `protobuf:"varint,4,opt,name=time_used,json=timeUsed,proto3" json:"time_used,omitempty"`
	MemoryUsed   int64       `protobuf:"varint,5,opt,name=memory_used,json=memoryUsed,proto3" json:"memory_used,omitempty"`
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_judge_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_judge_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_proto_judge_proto_rawDescGZIP(), []int{1}
}

func (x *TaskResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *TaskResult) GetStatus() JudgeStatus {
	if x != nil {
		return x.Status
	}
	return JudgeStatus_STATUS_UNSPECIFIED
}

func (x *TaskResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskResult) GetTimeUsed() int32 {
	if x != nil {
		return x.TimeUsed
	}
	return 0
}

func (x *TaskResult) GetMemoryUsed() int64 {
	if x != nil {
		return x.MemoryUsed
	}
	return 0
}

type TaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status     JudgeStatus `protobuf:"varint,1,opt,name=status,proto3,enum=deep_oj.JudgeStatus" json:"status,omitempty"`
	TimeUsed   int32       `protobuf:"varint,2,opt,name=time_used,json=timeUsed,proto3" json:"time_used,omitempty"`
	MemoryUsed int64       `protobuf:"varint,3,opt,name=memory_used,json=memoryUsed,proto3" json:"memory_used,omitempty"`
	Message    string      `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_judge_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_judge_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_judge_proto_rawDescGZIP(), []int{2}
}

func (x *TaskResponse) GetStatus() JudgeStatus {
	if x != nil {
		return x.Status
	}
	return JudgeStatus_STATUS_UNSPECIFIED
}

func (x *TaskResponse) GetTimeUsed() int32 {
	if x != nil {
		return x.TimeUsed
	}
	return 0
}

func (x *TaskResponse) GetMemoryUsed() int64 {
	if x != nil {
		return x.MemoryUsed
	}
	return 0
}

func (x *TaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ack) Reset() {
	*x = Ack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_judge_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_judge_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_judge_proto_rawDescGZIP(), []int{3}
}

var File_proto_judge_proto protoreflect.FileDescriptor

var file_proto_judge_proto_rawDesc = []byte{
	// Manual implementation placeholder for raw descriptor
}

var file_proto_judge_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_judge_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_judge_proto_goTypes = []interface{}{
	(Language)(0),        // 0: deep_oj.Language
	(JudgeStatus)(0),     // 1: deep_oj.JudgeStatus
	(*TaskRequest)(nil),  // 2: deep_oj.TaskRequest
	(*TaskResult)(nil),   // 3: deep_oj.TaskResult
	(*TaskResponse)(nil), // 4: deep_oj.TaskResponse
	(*Ack)(nil),          // 5: deep_oj.Ack
}
var file_proto_judge_proto_depIdxs = []int32{
	0, // 0: deep_oj.TaskRequest.language:type_name -> deep_oj.Language
	1, // 1: deep_oj.TaskResult.status:type_name -> deep_oj.JudgeStatus
	1, // 2: deep_oj.TaskResponse.status:type_name -> deep_oj.JudgeStatus
	2, // 3: deep_oj.JudgeService.ExecuteTask:input_type -> deep_oj.TaskRequest
	3, // 4: deep_oj.JudgeService.UpdateStatus:input_type -> deep_oj.TaskResult
	4, // 5: deep_oj.JudgeService.ExecuteTask:output_type -> deep_oj.TaskResponse
	5, // 6: deep_oj.JudgeService.UpdateStatus:output_type -> deep_oj.Ack
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_judge_proto_init() }
func file_proto_judge_proto_init() {
	if File_proto_judge_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_judge_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_judge_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_judge_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_judge_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_judge_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_judge_proto_goTypes,
		DependencyIndexes: file_proto_judge_proto_depIdxs,
		EnumInfos:         file_proto_judge_proto_enumTypes,
		MessageInfos:      file_proto_judge_proto_msgTypes,
	}.Build()
	File_proto_judge_proto = out.File
	file_proto_judge_proto_rawDesc = nil
	file_proto_judge_proto_goTypes = nil
	file_proto_judge_proto_depIdxs = nil
}
